/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PointAndClickTest;

/**
 *
 * @author Elijah
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoomOne = new javax.swing.JPanel();
        WallOne = new javax.swing.JPanel();
        FloorOne = new javax.swing.JPanel();
        DoorOne = new javax.swing.JPanel();
        RoomTwo = new javax.swing.JPanel();
        FloorTwo = new javax.swing.JPanel();
        DoorTwo = new javax.swing.JPanel();
        WallTwo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point and Click");
        setMinimumSize(new java.awt.Dimension(800, 350));
        setPreferredSize(new java.awt.Dimension(800, 350));
        getContentPane().setLayout(null);

        WallOne.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WallOneLayout = new javax.swing.GroupLayout(WallOne);
        WallOne.setLayout(WallOneLayout);
        WallOneLayout.setHorizontalGroup(
            WallOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        WallOneLayout.setVerticalGroup(
            WallOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        FloorOne.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout FloorOneLayout = new javax.swing.GroupLayout(FloorOne);
        FloorOne.setLayout(FloorOneLayout);
        FloorOneLayout.setHorizontalGroup(
            FloorOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FloorOneLayout.setVerticalGroup(
            FloorOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        DoorOne.setBackground(new java.awt.Color(0, 0, 0));
        DoorOne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 0, 51), null, null));
        DoorOne.setForeground(new java.awt.Color(255, 255, 255));
        DoorOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveToRoomTwo(evt);
            }
        });

        javax.swing.GroupLayout DoorOneLayout = new javax.swing.GroupLayout(DoorOne);
        DoorOne.setLayout(DoorOneLayout);
        DoorOneLayout.setHorizontalGroup(
            DoorOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        DoorOneLayout.setVerticalGroup(
            DoorOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RoomOneLayout = new javax.swing.GroupLayout(RoomOne);
        RoomOne.setLayout(RoomOneLayout);
        RoomOneLayout.setHorizontalGroup(
            RoomOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WallOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(FloorOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RoomOneLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(DoorOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RoomOneLayout.setVerticalGroup(
            RoomOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomOneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(RoomOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomOneLayout.createSequentialGroup()
                        .addComponent(WallOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(FloorOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RoomOneLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(DoorOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(RoomOne);
        RoomOne.setBounds(0, 0, 800, 350);

        RoomTwo.setEnabled(false);
        RoomTwo.setVisible(false);
        RoomTwo.setEnabled(false);

        FloorTwo.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout FloorTwoLayout = new javax.swing.GroupLayout(FloorTwo);
        FloorTwo.setLayout(FloorTwoLayout);
        FloorTwoLayout.setHorizontalGroup(
            FloorTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FloorTwoLayout.setVerticalGroup(
            FloorTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        DoorTwo.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout DoorTwoLayout = new javax.swing.GroupLayout(DoorTwo);
        DoorTwo.setLayout(DoorTwoLayout);
        DoorTwoLayout.setHorizontalGroup(
            DoorTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        DoorTwoLayout.setVerticalGroup(
            DoorTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        WallTwo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout WallTwoLayout = new javax.swing.GroupLayout(WallTwo);
        WallTwo.setLayout(WallTwoLayout);
        WallTwoLayout.setHorizontalGroup(
            WallTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        WallTwoLayout.setVerticalGroup(
            WallTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout RoomTwoLayout = new javax.swing.GroupLayout(RoomTwo);
        RoomTwo.setLayout(RoomTwoLayout);
        RoomTwoLayout.setHorizontalGroup(
            RoomTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WallTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(FloorTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(RoomTwoLayout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(DoorTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RoomTwoLayout.setVerticalGroup(
            RoomTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoomTwoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(RoomTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RoomTwoLayout.createSequentialGroup()
                        .addComponent(WallTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(FloorTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RoomTwoLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(DoorTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        getContentPane().add(RoomTwo);
        RoomTwo.setBounds(0, 0, 800, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moveToRoomTwo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveToRoomTwo
        // TODO add your handling code here:
        RoomOne.setVisible(false);
        RoomOne.setEnabled(false);
        
        RoomTwo.setVisible(true);
        RoomTwo.setEnabled(true);
    }//GEN-LAST:event_moveToRoomTwo

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoorOne;
    private javax.swing.JPanel DoorTwo;
    private javax.swing.JPanel FloorOne;
    private javax.swing.JPanel FloorTwo;
    private javax.swing.JPanel RoomOne;
    private javax.swing.JPanel RoomTwo;
    private javax.swing.JPanel WallOne;
    private javax.swing.JPanel WallTwo;
    // End of variables declaration//GEN-END:variables
}
